version: 2.1

jobs:
  # A successful job
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: This will pass
          command: |
            echo "This job is supposed to pass....."
            exit 0

  build2:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: This will pass
          command: |
            echo "This job is supposed to pass....."
            exit 0            

  # A job that will fail
  fail_job:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          shell: /bin/sh +e pipefail
          name: This will fail
          command: |
            echo "This job is supposed to fail."
            exit 1

      - run:
          when: on_fail
          command: |
            echo "Make it pass"
            exit 0

  # Another successful job
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy
          command: |
            echo "Deploying application..."
            # Add your deployment commands here

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build2:
          filters:
            tags:
              only:
              - /.*/
            branches:
              ignore: /.*/
      - fail_job
      - deploy:
          requires:
            - build
